services:
  postgres:
    image: postgres:16
    container_name: internflow_db
    restart: always
    environment:
      POSTGRES_USER: internflow_user
      POSTGRES_PASSWORD: internflow_password
      POSTGRES_DB: internflow_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
